### PR TITLE
fix(loop-protect): fix loop-protect logic to account for multiple loops

### LINKED ISSUE #45: fix loop-protect bug

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
closes #45

### CODE REVIEW

File: src/utils/test/challenge/eval-code-run-tests.js [hunk 1]
```diff
@@ -1,35 +1,41 @@
...
-    // if suppressTests is true, only eval code,
-    // otherwise, eval code and run tests (if tests exist)
-    if (!SUPPRESS_TESTS.test(code) && TESTS[id]) {
-      tests = prepend + JSON.stringify(TESTS[id].tests)
-      if (TESTS[id].tail) tail += TESTS[id].tail
-    }
-    
-    // eslint-disable-next-line
-    eval(
-      loopProtect(code) +
```
Comment (no-stack-dub-sack) [inline src/utils/test/challenge/eval-code-run-tests.js]: for some reason this caused problems with loop-free code. Tests would multiply (like 700 of them) and they would all log as `Fail: undefined`. I couldn't really see why this was happening, but figured out that eval'ing the user code on its own without the tests prevented this, so devised a way to test code first for loops, then if infinite-loop free, go on to test. Throw custom error if infinite loop. Simultaneously realized that replacement logic wouldn't work if multiple loops were present, so fixed that as well.
